### ISSUE TITLE
Error executing spiceweasel

### ISSUE THREAD

**Issue by sudhanshusd** [mattray/spiceweasel#91]
Hello,

I am trying to setup auto-deployment for my chef cookbooks,  using combination of spiceweasel and berkshelf tools.
For my testing , I have a single cookbook in my local  git repository. 
I'm getting error while executing spiceweasel. 
I find that cookbook is cloned from git repository into the local "**~/.berkshelf/cookbooks**" directory . However, it is not uploaded to the chef server.

Environment details:
OS : Amazon Linux AMI release 2016.09
Ruby: ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
spiceweasel (2.6.0)
berkshelf (2.0.17)

Please let me know if any more information is needed.

The debug mode output as below:

========================================================
[root@ip-10-0-0-224 ci]# bundle exec spiceweasel -e spiceweasel.yml --debug
DEBUG: file: spiceweasel.yml
DEBUG: file manifest: {"berksfile"=>{"options"=>"-d --force --no-freeze --halt-on-frozen --skip-syntax-check"}, "roles"=>nil, "data bags"=>nil}
DEBUG: berkshelf resolving dependencies: {"berksfile"=>"./Berksfile", "no_freeze"=>true, "force"=>true, "skip_syntax_check"=>true, "skip_dependencies"=>false, "halt_on_frozen"=>true}
DEBUG: ["knife bootstrap [SSH_USER@]FQDN (options)", "knife client bulk delete REGEX (options)", "knife client create CLIENTNAME (options)", "knife client delete CLIENT (options)", "knife client edit CLIENT (options)", "knife client key delete CLIENT KEYNAME (options)", "knife client key edit CLIENT KEYNAME (options)", "knife client key list CLIENT (options)", "knife client key show CLIENT KEYNAME (options)", "knife client list (options)", "knife client reregister CLIENT (options)", "knife client show CLIENT (options)", "knife configure (options)", "knife configure client DIRECTORY", "knife cookbook bulk delete REGEX (options)", "knife cookbook create COOKBOOK (options)", "knife cookbook delete COOKBOOK VERSION (options)", "knife cookbook download COOKBOOK [VERSION] (options)", "knife cookbook list (options)", "knife cookbook metadata COOKBOOK (options)", "knife cookbook metadata from FILE (options)", "knife cookbook show COOKBOOK [VERSION] [PART] [FILENAME] (options)", "knife cookbook test [COOKBOOKS...] (options)", "knife cookbook upload [COOKBOOKS...] (options)", "knife cookbook site download COOKBOOK [VERSION] (options)", "knife cookbook site install COOKBOOK [VERSION] (options)", "knife cookbook site list (options)", "knife cookbook site search QUERY (options)", "knife cookbook site share COOKBOOK [CATEGORY] (options)", "knife cookbook site show COOKBOOK [VERSION] (options)", "knife cookbook site unshare COOKBOOK", "knife data bag create BAG [ITEM] (options)", "knife data bag delete BAG [ITEM] (options)", "knife data bag edit BAG ITEM (options)", "knife data bag from file BAG FILE|FOLDER [FILE|FOLDER..] (options)", "knife data bag list (options)", "knife data bag show BAG [ITEM] (options)", "knife environment compare [ENVIRONMENT..] (options)", "knife environment create ENVIRONMENT (options)", "knife environment delete ENVIRONMENT (options)", "knife environment edit ENVIRONMENT (options)", "knife environment from file FILE [FILE..] (options)", "knife environment list (options)", "knife environment show ENVIRONMENT (options)", "knife exec [SCRIPT] (options)", "knife help [list|TOPIC]", "knife index rebuild (options)", "knife node bulk delete REGEX (options)", "knife node create NODE (options)", "knife node delete NODE (options)", "knife node edit NODE (options)", "knife node environment set NODE ENVIRONMENT", "knife node from file FILE (options)", "knife node list (options)", "knife node run_list add [NODE] [ENTRY[,ENTRY]] (options)", "knife node run_list remove [NODE] [ENTRY[,ENTRY]] (options)", "knife node run_list set NODE ENTRIES (options)", "knife node show NODE (options)", "knife null", "knife osc_user create USER (options)", "knife osc_user delete USER (options)", "knife osc_user edit USER (options)", "knife osc_user list (options)", "knife osc_user reregister USER (options)", "knife osc_user show USER (options)", "knife delete [PATTERN1 ... PATTERNn]", "knife deps PATTERN1 [PATTERNn]", "knife diff PATTERNS", "knife download PATTERNS", "knife edit [PATTERN1 ... PATTERNn]", "knife list [-dfR1p] [PATTERN1 ... PATTERNn]", "knife show [PATTERN1 ... PATTERNn]", "knife upload PATTERNS", "knife xargs [COMMAND]", "knife raw REQUEST_PATH", "knife recipe list [PATTERN]", "knife rehash", "knife role bulk delete REGEX (options)", "knife role create ROLE (options)", "knife role delete ROLE (options)", "knife role edit ROLE (options)", "knife role env_run_list add [ROLE] [ENVIRONMENT] [ENTRY[,ENTRY]] (options)", "knife role env_run_list clear [ROLE] [ENVIRONMENT]", "knife role env_run_list remove [ROLE] [ENVIRONMENT] [ENTRIES]", "knife role env_run_list replace [ROLE] [ENVIRONMENT] [OLD_ENTRY] [NEW_ENTRY] ", "knife role env_run_list set [ROLE] [ENVIRONMENT] [ENTRIES]", "knife role from file FILE [FILE..] (options)", "knife role list (options)", "knife role run_list add [ROLE] [ENTRY[,ENTRY]] (options)", "knife role run_list clear [ROLE]", "knife role run_list remove [ROLE] [ENTRY]", "knife role run_list replace [ROLE] [OLD_ENTRY] [NEW_ENTRY] ", "knife role run_list set [ROLE] [ENTRIES]", "knife role show ROLE (options)", "knife search INDEX QUERY (options)", "knife serve (options)", "knife ssh QUERY COMMAND (options)", "knife ssl check [URL] (options)", "knife ssl fetch [URL] (options)", "knife status QUERY (options)", "knife supermarket download COOKBOOK [VERSION] (options)", "knife supermarket install COOKBOOK [VERSION] (options)", "knife supermarket list (options)", "knife supermarket search QUERY (options)", "knife supermarket share COOKBOOK [CATEGORY] (options)", "knife supermarket show COOKBOOK [VERSION] (options)", "knife supermarket unshare COOKBOOK (options)", "knife tag create NODE TAG ...", "knife tag delete NODE TAG ...", "knife tag list NODE", "knife user create USERNAME DISPLAY_NAME FIRST_NAME LAST_NAME EMAIL PASSWORD (options)", "knife user delete USER (options)", "knife user edit USER (options)", "knife user key create USER (options)", "knife user key delete USER KEYNAME (options)", "knife user key edit USER KEYNAME (options)", "knife user key list USER (options)", "knife user key show USER KEYNAME (options)", "knife user list (options)", "knife user reregister USER (options)", "knife user show USER (options)"]
DEBUG: Command will timeout after 300 seconds.
Celluloid 0.17.3 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
Using Chefignore at '/root/.berkshelf/cookbooks/TESTandDELETE-f88da61b4070b6a939869a3a0ad5304db67ecb78/chefignore'
Installing TESTandDELETE (0.1.0) from git: 'ssh://git@newsource.accenture.com/a1703/TESTandDELETE.git' with branch: 'master' at ref: 'f88da61b4070b6a939869a3a0ad5304db67ecb78'
/usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:35:in `terminate': task was terminated (Celluloid::TaskTerminated)
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:323:in `block in cleanup'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `each'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `cleanup'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:307:in `shutdown'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:299:in `handle_crash'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:171:in `rescue in run'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:150:in `run'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `call'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
        from (celluloid):0:in `remote procedure call'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:12:in `_send_'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid.rb:196:in `new'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/ridley-1.7.1/lib/ridley/client.rb:162:in `initialize'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:12:in `_send_'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid.rb:196:in `new'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/ridley-1.7.1/lib/ridley.rb:27:in `new'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/lib/berkshelf/berksfile.rb:717:in `ridley_connection'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/lib/berkshelf/berksfile.rb:526:in `upload'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/lib/berkshelf/cli.rb:230:in `upload'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/lib/berkshelf/cli.rb:21:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/bin/berks:6:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.4/bin/berks:23:in `load'
        from /usr/local/rvm/gems/ruby-2.2.4/bin/berks:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
Celluloid 0.17.3 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
/usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:35:in `terminate': task was terminated (Celluloid::TaskTerminated)
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:323:in `block in cleanup'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `each'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `cleanup'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:307:in `shutdown'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:299:in `handle_crash'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:171:in `rescue in run'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:150:in `run'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `call'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
        from (celluloid):0:in `remote procedure call'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:12:in `_send_'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid.rb:196:in `new'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/ridley-1.7.1/lib/ridley/client.rb:162:in `initialize'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:12:in `_send_'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid.rb:196:in `new'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/ridley-1.7.1/lib/ridley.rb:27:in `new'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/lib/berkshelf/berksfile.rb:717:in `ridley_connection'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/lib/berkshelf/berksfile.rb:526:in `upload'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/lib/berkshelf/cli.rb:230:in `upload'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/lib/berkshelf/cli.rb:21:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/bin/berks:6:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.4/bin/berks:23:in `load'
        from /usr/local/rvm/gems/ruby-2.2.4/bin/berks:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
DEBUG: #<Spiceweasel::Command:0x00000004fb0c58 @command="berks upload -d --force --no-freeze --halt-on-frozen --skip-syntax-check -b ./Berksfile", @options={}, @timeout=nil, @allow_failure=        true>
DEBUG: Using Chefignore at '/root/.berkshelf/cookbooks/TESTandDELETE-f88da61b4070b6a939869a3a0ad5304db67ecb78/chefignore'
Installing TESTandDELETE (0.1.0) from git: 'ssh://git@newsource.accenture.com/a1703/TESTandDELETE.git' with branch: 'master' at ref: 'f88da61b4070b6a939869a3a0ad5304db67ecb78'

FATAL: Celluloid 0.17.3 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
/usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:35:in `terminate': task was terminated (Celluloid::TaskTerminated)
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:323:in `block in cleanup'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `each'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:321:in `cleanup'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:307:in `shutdown'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:299:in `handle_crash'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:171:in `rescue in run'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:150:in `run'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:131:in `block in start'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `call'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
        from (celluloid):0:in `remote procedure call'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:12:in `_send_'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid.rb:196:in `new'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/ridley-1.7.1/lib/ridley/client.rb:162:in `initialize'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
        from (celluloid):0:in `remote procedure call'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid/proxy/cell.rb:12:in `_send_'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/celluloid-0.17.3/lib/celluloid.rb:196:in `new'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/ridley-1.7.1/lib/ridley.rb:27:in `new'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/lib/berkshelf/berksfile.rb:717:in `ridley_connection'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/lib/berkshelf/berksfile.rb:526:in `upload'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/lib/berkshelf/cli.rb:230:in `upload'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/lib/berkshelf/cli.rb:21:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /usr/local/rvm/gems/ruby-2.2.4/gems/berkshelf-2.0.17/bin/berks:6:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.4/bin/berks:23:in `load'
        from /usr/local/rvm/gems/ruby-2.2.4/bin/berks:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'

========================================================

Regards,
Sudhanshu

**Comment by mattray** [comment]
It looks like it's having an issue with the older version of Berkshelf's Celluloid dependency. I was just looking at refreshing it to work with Ruby 2.3.1, maybe I can bump all the dependencies forward and see how it behaves.
